categories:
  - title: '✨ Features'
    labels:
      - 'feature'
  - title: '🚀 Performance'
    labels:
      - 'performance'
  - title: '🪲 Bug Fixes'
    labels:
      - 'bug'
  - title: '🔨 Build'
    labels:
      - 'build'
  - title: '📘 Documentation'
    labels:
      - 'documentation'
  - title: '✅ Testing'
    labels:
      - 'testing'
      - 'ci'
  - title: '♻️ Refactoring'
    labels:
      - 'refactoring'
  - title: '🎨 Style'
    labels:
      - 'style'
  - title: '🧹 Chores'
    labels:
      - 'chore'
template: |
  ## What’s Changed

  $CHANGES
# Conventional Commits-style PR titles: <type>[(scope)][!]: <description>
# https://www.conventionalcommits.org/en/v1.0.0-beta.4/
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\([^)]+\))?!?:/i'
      - '/^feature(\([^)]+\))?!?:/i'
      - '/^enhancement(\([^)]+\))?!?:/i'
  - label: 'performance'
    title:
      - '/^perf(\([^)]+\))?!?:/i'
      - '/^performance(\([^)]+\))?!?:/i'
  - label: 'bug'
    title:
      - '/^fix(\([^)]+\))?!?:/i'
      - '/^bugfix(\([^)]+\))?!?:/i'
      - '/^bug(\([^)]+\))?!?:/i'
  - label: 'build'
    title:
      - '/^build(\([^)]+\))?!?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\([^)]+\))?!?:/i'
      - '/^documentation(\([^)]+\))?!?:/i'
      - '/^doc(\([^)]+\))?!?:/i'
  - label: 'testing'
    title:
      - '/^tests(\([^)]+\))?!?:/i'
      - '/^test(\([^)]+\))?!?:/i'
      - '/^testing(\([^)]+\))?!?:/i'
  - label: 'ci'
    title:
      - '/^ci(\([^)]+\))?!?:/i'
  - label: 'refactoring'
    title:
      - '/^refactoring(\([^)]+\))?!?:/i'
      - '/^refactor(\([^)]+\))?!?:/i'
  - label: 'style'
    title:
      - '/^style(\([^)]+\))?!?:/i'
      - '/^whitespace(\([^)]+\))?!?:/i'
  - label: 'chore'
    title:
      - '/^chore(\([^)]+\))?!?:/i'
      - '/^chores(\([^)]+\))?!?:/i'
