# Integration test cases: same set as tools/integration_tests.py TEST_CASES.
# Each call: pcb2gcode_add_integration_test(ctest_name input_path exit_code [--arg1] [--arg2] ...)
# input_path is relative to CMAKE_SOURCE_DIR.

set(IT_EXAMPLES "tests/data/gerbv_example")
set(IT_BROKEN "tests/data/broken_examples")

function(pcb2gcode_add_integration_test name input_path exit_code)
  set(_args "${ARGN}")
  set(_cmd "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tools/run_one_integration_test.py"
    --pcb2gcode "$<TARGET_FILE:pcb2gcode>"
    --input-dir "${CMAKE_SOURCE_DIR}/${input_path}"
    --exit-code ${exit_code})
  foreach(_a IN LISTS _args)
    list(APPEND _cmd --arg "${_a}")
  endforeach()
  add_test(NAME "integration_${name}" COMMAND ${_cmd})
  set_tests_properties("integration_${name}" PROPERTIES WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
endfunction()

# Standard example tests (path_name, [], 0)
pcb2gcode_add_integration_test(am-test "${IT_EXAMPLES}/am-test" 0)
pcb2gcode_add_integration_test(am-test-counterclockwise "${IT_EXAMPLES}/am-test-counterclockwise" 0)
pcb2gcode_add_integration_test(am-test-extended "${IT_EXAMPLES}/am-test-extended" 0)
pcb2gcode_add_integration_test(am-test-millinfeed "${IT_EXAMPLES}/am-test-millinfeed" 0)
pcb2gcode_add_integration_test(am-test-voronoi "${IT_EXAMPLES}/am-test-voronoi" 0)
pcb2gcode_add_integration_test(am-test-voronoi-extra-passes "${IT_EXAMPLES}/am-test-voronoi-extra-passes" 0)
pcb2gcode_add_integration_test(am-test-voronoi-front "${IT_EXAMPLES}/am-test-voronoi-front" 0)
pcb2gcode_add_integration_test(am-test-voronoi-wide-extra-passes "${IT_EXAMPLES}/am-test-voronoi-wide-extra-passes" 0)
pcb2gcode_add_integration_test(backtrack "${IT_EXAMPLES}/backtrack" 0)
pcb2gcode_add_integration_test(backtrack_0 "${IT_EXAMPLES}/backtrack_0" 0)
pcb2gcode_add_integration_test(D1MiniGSR "${IT_EXAMPLES}/D1MiniGSR" 0)
pcb2gcode_add_integration_test(Easy-SDR_HF_Upconverter_SMD_Gerbers "${IT_EXAMPLES}/Easy-SDR_HF_Upconverter_SMD_Gerbers" 0)
pcb2gcode_add_integration_test(edge-cuts-broken-loop "${IT_EXAMPLES}/edge-cuts-broken-loop" 0)
pcb2gcode_add_integration_test(edge-cuts-inside-cuts "${IT_EXAMPLES}/edge-cuts-inside-cuts" 0)
pcb2gcode_add_integration_test(example_board_new_default "${IT_EXAMPLES}/example_board_new_default" 0)
pcb2gcode_add_integration_test(example_board_new_mirror_x "${IT_EXAMPLES}/example_board_new_mirror_x" 0)
pcb2gcode_add_integration_test(example_board_new_mirror_y "${IT_EXAMPLES}/example_board_new_mirror_y" 0)
pcb2gcode_add_integration_test(example_board_new_mirror_y_drill_back "${IT_EXAMPLES}/example_board_new_mirror_y_drill_back" 0)
pcb2gcode_add_integration_test(example_board_new_zero_start "${IT_EXAMPLES}/example_board_new_zero_start" 0)
pcb2gcode_add_integration_test(example_board_al_custom "${IT_EXAMPLES}/example_board_al_custom" 0)
pcb2gcode_add_integration_test(example_board_al_custom_tiled "${IT_EXAMPLES}/example_board_al_custom_tiled" 0)
pcb2gcode_add_integration_test(example_board_al_linuxcnc "${IT_EXAMPLES}/example_board_al_linuxcnc" 0)
pcb2gcode_add_integration_test(example_board_al_linuxcnc_tiled "${IT_EXAMPLES}/example_board_al_linuxcnc_tiled" 0)
pcb2gcode_add_integration_test(example_board_al_mach3 "${IT_EXAMPLES}/example_board_al_mach3" 0)
pcb2gcode_add_integration_test(example_board_al_mach3_tiled "${IT_EXAMPLES}/example_board_al_mach3_tiled" 0)
pcb2gcode_add_integration_test(example_board_al_mach4 "${IT_EXAMPLES}/example_board_al_mach4" 0)
pcb2gcode_add_integration_test(example_board_al_mach4_tiled "${IT_EXAMPLES}/example_board_al_mach4_tiled" 0)
pcb2gcode_add_integration_test(invert_gerbers "${IT_EXAMPLES}/invert_gerbers" 0)
pcb2gcode_add_integration_test(invert_gerbers_fill "${IT_EXAMPLES}/invert_gerbers_fill" 0)
pcb2gcode_add_integration_test(KeyboardControllerM102 "${IT_EXAMPLES}/KeyboardControllerM102" 0)
pcb2gcode_add_integration_test(KNoT-Gateway_Mini_Starter_Board "${IT_EXAMPLES}/KNoT-Gateway Mini Starter Board" 0)
pcb2gcode_add_integration_test(KNoT_Thing_Starter_Board "${IT_EXAMPLES}/KNoT_Thing_Starter_Board" 0)
pcb2gcode_add_integration_test(lift-mill "${IT_EXAMPLES}/lift-mill" 0)
pcb2gcode_add_integration_test(mill_masking "${IT_EXAMPLES}/mill_masking" 0)
pcb2gcode_add_integration_test(mill_masking_voronoi "${IT_EXAMPLES}/mill_masking_voronoi" 0)
pcb2gcode_add_integration_test(milldrilldiatest "${IT_EXAMPLES}/milldrilldiatest" 0)
pcb2gcode_add_integration_test(milldrilldiatest_units "${IT_EXAMPLES}/milldrilldiatest_units" 0)
pcb2gcode_add_integration_test(multivibrator "${IT_EXAMPLES}/multivibrator" 0)
pcb2gcode_add_integration_test(multivibrator-basename "${IT_EXAMPLES}/multivibrator-basename" 0)
pcb2gcode_add_integration_test(multivibrator-clockwise "${IT_EXAMPLES}/multivibrator-clockwise" 0)
pcb2gcode_add_integration_test(multivibrator-contentions "${IT_EXAMPLES}/multivibrator-contentions" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes "${IT_EXAMPLES}/multivibrator-extra-passes" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes-big "${IT_EXAMPLES}/multivibrator-extra-passes-big" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes-two-isolators "${IT_EXAMPLES}/multivibrator-extra-passes-two-isolators" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes-two-isolators-tiles "${IT_EXAMPLES}/multivibrator-extra-passes-two-isolators-tiles" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes-two-isolators-tiles-al "${IT_EXAMPLES}/multivibrator-extra-passes-two-isolators-tiles-al" 0)
pcb2gcode_add_integration_test(multivibrator-extra-passes-voronoi "${IT_EXAMPLES}/multivibrator-extra-passes-voronoi" 0)
pcb2gcode_add_integration_test(multivibrator-identical-isolators "${IT_EXAMPLES}/multivibrator-identical-isolators" 0)
pcb2gcode_add_integration_test(multivibrator-no-tsp-2opt "${IT_EXAMPLES}/multivibrator-no-tsp-2opt" 0)
pcb2gcode_add_integration_test(multivibrator-no-zbridges "${IT_EXAMPLES}/multivibrator-no-zbridges" 0)
pcb2gcode_add_integration_test(multivibrator-two-isolators "${IT_EXAMPLES}/multivibrator-two-isolators" 0)
pcb2gcode_add_integration_test(multivibrator_backtrack "${IT_EXAMPLES}/multivibrator_backtrack" 0)
pcb2gcode_add_integration_test(multivibrator_milldrill_nom6 "${IT_EXAMPLES}/multivibrator_milldrill_nom6" 0)
pcb2gcode_add_integration_test(multivibrator_no_export "${IT_EXAMPLES}/multivibrator_no_export" 0)
pcb2gcode_add_integration_test(multivibrator_no_export_milldrill "${IT_EXAMPLES}/multivibrator_no_export_milldrill" 0)
pcb2gcode_add_integration_test(multivibrator_no_optimise "${IT_EXAMPLES}/multivibrator_no_optimise" 0)
pcb2gcode_add_integration_test(multivibrator_no_zero_start "${IT_EXAMPLES}/multivibrator_no_zero_start" 0)
pcb2gcode_add_integration_test(multivibrator_nom6 "${IT_EXAMPLES}/multivibrator_nom6" 0)
pcb2gcode_add_integration_test(multivibrator_pre_post_milling_gcode "${IT_EXAMPLES}/multivibrator_pre_post_milling_gcode" 0)
pcb2gcode_add_integration_test(multivibrator_xy_offset "${IT_EXAMPLES}/multivibrator_xy_offset" 0)
pcb2gcode_add_integration_test(multivibrator_xy_offset_zero_start "${IT_EXAMPLES}/multivibrator_xy_offset_zero_start" 0)
pcb2gcode_add_integration_test(multivibrator-zchange-absolute "${IT_EXAMPLES}/multivibrator-zchange-absolute" 0)
pcb2gcode_add_integration_test(multi_outline "${IT_EXAMPLES}/multi_outline" 0)
pcb2gcode_add_integration_test(null_drill "${IT_EXAMPLES}/null_drill" 0)
pcb2gcode_add_integration_test(overlapping_edge_cuts "${IT_EXAMPLES}/overlapping_edge_cuts" 0)
pcb2gcode_add_integration_test(project-controller "${IT_EXAMPLES}/project-controller" 0)
pcb2gcode_add_integration_test(Rotary-Encoder-Breakout "${IT_EXAMPLES}/Rotary-Encoder-Breakout" 0)
pcb2gcode_add_integration_test(round_pcb_3 "${IT_EXAMPLES}/round_pcb_3" 0)
pcb2gcode_add_integration_test(round_pcb_4 "${IT_EXAMPLES}/round_pcb_4" 0)
pcb2gcode_add_integration_test(round_pcb_5 "${IT_EXAMPLES}/round_pcb_5" 0)
pcb2gcode_add_integration_test(shaped_pcb "${IT_EXAMPLES}/shaped_pcb" 0)
pcb2gcode_add_integration_test(sharp_corner "${IT_EXAMPLES}/sharp_corner" 0)
pcb2gcode_add_integration_test(sharp_corner_2 "${IT_EXAMPLES}/sharp_corner_2" 0)
pcb2gcode_add_integration_test(sharp_corner_2_offset "${IT_EXAMPLES}/sharp_corner_2_offset" 0)
pcb2gcode_add_integration_test(sharp_corner_big_isolation_width "${IT_EXAMPLES}/sharp_corner_big_isolation_width" 0)
pcb2gcode_add_integration_test(silk "${IT_EXAMPLES}/silk" 0)
pcb2gcode_add_integration_test(silk-lines "${IT_EXAMPLES}/silk-lines" 0)
pcb2gcode_add_integration_test(slots-milldrill "${IT_EXAMPLES}/slots-milldrill" 0)
pcb2gcode_add_integration_test(slots-milldrill-metric "${IT_EXAMPLES}/slots-milldrill-metric" 0)
pcb2gcode_add_integration_test(slots-with-drill "${IT_EXAMPLES}/slots-with-drill" 0)
pcb2gcode_add_integration_test(slots-with-drill-and-milldrill "${IT_EXAMPLES}/slots-with-drill-and-milldrill" 0)
pcb2gcode_add_integration_test(slots-with-drill-metric "${IT_EXAMPLES}/slots-with-drill-metric" 0)
pcb2gcode_add_integration_test(slots-with-drills-available "${IT_EXAMPLES}/slots-with-drills-available" 0)

# split config csv
pcb2gcode_add_integration_test(split_config_csv "${IT_BROKEN}/split_config" 0 "--config=millproject,millproject2")

# bad output dir (expect exit 1)
pcb2gcode_add_integration_test(bad_output_dir_multivibrator "${IT_EXAMPLES}/multivibrator" 1 "--output-dir=/tmp/nonexistantpath")
pcb2gcode_add_integration_test(bad_output_dir_slots-with-drill "${IT_EXAMPLES}/slots-with-drill" 1 "--output-dir=/tmp/nonexistantpath")
pcb2gcode_add_integration_test(bad_output_dir_slots-milldrill "${IT_EXAMPLES}/slots-milldrill" 1 "--output-dir=/tmp/nonexistantpath")

# split config with two --config args
pcb2gcode_add_integration_test(split_config_two "${IT_BROKEN}/split_config" 0 "--config=millproject" "--config=millproject2")

# split config with no config (expect exit 14)
pcb2gcode_add_integration_test(split_config_fail "${IT_BROKEN}/split_config" 14)

# multivibrator_bad_* (expect exit 100)
pcb2gcode_add_integration_test(multivibrator_bad_front "${IT_EXAMPLES}/multivibrator" 100 "--front=non_existant_file")
pcb2gcode_add_integration_test(multivibrator_bad_back "${IT_EXAMPLES}/multivibrator" 100 "--back=non_existant_file")
pcb2gcode_add_integration_test(multivibrator_bad_outline "${IT_EXAMPLES}/multivibrator" 100 "--outline=non_existant_file")
pcb2gcode_add_integration_test(multivibrator_bad_drill "${IT_EXAMPLES}/multivibrator" 100 "--drill=non_existant_file")

# broken invalid-config (expect exit 100)
pcb2gcode_add_integration_test(broken_invalid-config "${IT_BROKEN}/invalid-config" 100)

# version / help (exit 0)
pcb2gcode_add_integration_test(version "${IT_EXAMPLES}" 0 "--version")
pcb2gcode_add_integration_test(help "${IT_EXAMPLES}" 0 "--help")

# tsp_2opt_with_millfeedirection (exit 100)
pcb2gcode_add_integration_test(tsp_2opt_with_millfeedirection "${IT_EXAMPLES}/am-test" 100 "--tsp-2opt" "--mill-feed-direction=climb")

# g64_and_tolerance (exit 49)
pcb2gcode_add_integration_test(g64_and_tolerance "${IT_EXAMPLES}/am-test" 49 "--g64=5" "--tolerance=123")

# negative_spinup (exit 52)
pcb2gcode_add_integration_test(negative_spinup "${IT_EXAMPLES}/am-test" 52 "--spinup-time=-5")

# zero_millinfeed (exit 55)
pcb2gcode_add_integration_test(zero_millinfeed "${IT_EXAMPLES}/am-test" 55 "--mill-infeed=0")

# ignore warnings
pcb2gcode_add_integration_test(ignore_warnings "${IT_BROKEN}/invalid-config" 0 "--ignore-warnings")

# provided config
pcb2gcode_add_integration_test(provided_config "${IT_EXAMPLES}/am-test" 0 "--config=millproject")

# missing config (exit 100)
pcb2gcode_add_integration_test(missing_config "${IT_EXAMPLES}/am-test" 100 "--config=millproject_file_does_not_exist")

# invalid_millfeedirection (exit 101)
pcb2gcode_add_integration_test(invalid_millfeedirection "${IT_EXAMPLES}" 101 "--mill-feed-direction=invalid_value")

# zchange_below_zdrill (exit 19)
pcb2gcode_add_integration_test(zchange_below_zdrill "${IT_EXAMPLES}/multivibrator-zchange-absolute" 19 "--zchange-absolute=false")
